name: calendar_flutter_mcp_server
description: Calendar Flutter MCP Server
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.4
  dio: ^5.4.0
  json_annotation: ^4.9.0
  mcp_dart: ^0.5.1

executables:
  calendar_flutter_mcp_server:
dev_dependencies:
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
